### PR TITLE
Designed forgot password page

### PR DESCRIPTION
**Pull request by ritikraj2425**
##fixes issue #8 
##Changes Proposed
[x]Designed Forgot Password Page

Screenshot 2024-10-21 at 2 10 51 AM

### CODE REVIEW

**Comment by Dipeshdahiya** [comment]
just give me some time to review , i will update you in short

**Comment by ritikraj2425** [comment]
> just give me some time to review , i will update you in short

Sure.
If you have more work you can assign it to me

**Comment by Dipeshdahiya** [comment]
their is a small issue needed , can you redesign the login and signup sections and the social(Google and github)
Screenshot 2024-10-22 151407

i have attached a sample design i want for them 
just have a look and create a similar one

**Comment by aa7517641** [comment]
👍

**Comment by Dipeshdahiya** [comment]
if you think this will be a very large issue to work on , then you can work seperatly on signup and login page separatly , this will benifit you in checking 2 PR's at once , just create 2 new issues one for signup and another for login

**Comment by Dipeshdahiya** [comment]
the one who create the issue first will be assigned for it

**Pull request merged**
