### PR TITLE
redesigned signup page

### PR DESCRIPTION
**Pull request by ritikraj2425**
Fixes Issue #48 
##Redesigned signup page
Screenshot 2024-10-28 at 10 08 14 PM
 Page

### CODE REVIEW

**Comment by Dipeshdahiya** [comment]
please resolve the error , and descrese the size of the buttons as well as use the logo of google " G " instead of " Google "

**Comment by ritikraj2425** [comment]
Screenshot 2024-10-30 at 9 50 41 PM
I have made the changes you can see it once

**Comment by ritikraj2425** [comment]
please add hacktoberfest tag

**Comment by Dipeshdahiya** [comment]
pls resolve the conflicts

**Comment by ritikraj2425** [comment]
conflict solved

**Pull request merged**
